# Use an official Node.js runtime as the base image
FROM node:18 as backend

# Set the working directory in the container
WORKDIR /app

# Copy the backend application files to the container
COPY ./package.json ./package-lock.json ./

# Install backend dependencies
RUN npm install

# Copy the rest of the backend application files to the container
COPY . ./

# Expose the port your backend application
EXPOSE 3000
EXPOSE 3001

# Start the backend application when the container runs
CMD ["npm", "run", "start"]

# Create a new stage for Nginx
FROM nginx:alpine

# Copy Nginx configuration file to the container
COPY nginx/default.conf /etc/nginx/conf.d/default.conf

# Expose the port Nginx is listening on 80
EXPOSE 80

# Copy the built backend application from the previous stage
COPY --from=backend /app /usr/share/nginx/html

# Start Nginx when the container runs
CMD ["nginx", "-g", "daemon off;"]
