# Use an official Node.js runtime as the base image
FROM node:18

# Set the working directory in the container
WORKDIR /app

# Copy the backend application files to the container
COPY ./backend/package.json ./backend/package-lock.json ./

# Install backend dependencies
RUN npm install

# Copy the rest of the backend application files to the container
COPY ./backend ./

# Expose the port your backend application listens on (e.g., 3000)
EXPOSE 3000
EXPOSE 3001

# Start the backend application when the container runs
CMD ["npm", "run", "start"]
